{application,controller,
             [{description,"An OTP application"},
              {vsn,"0.1.0"},
              {registered,[]},
              {mod,{controller_app,[]}},
              {applications,[kernel,stdlib]},
              {env,[]},
              {modules,[controller_app,controller_server,controller_sup,
                        lib_appl,lib_vm,orchestrate]},
              {licenses,["Apache 2.0"]},
              {links,[]}]}.
